'use strict'

const datas = [
  {name: 'アンイシュワルダ', nickname: '地啼龍', weak1: '氷', weak2: 'なし',  breakPoint: '頭' },
  {name: 'アンジャナフ', nickname: '蛮顎竜', weak1: '水', weak2: '氷',  breakPoint: '鼻・翼' },
  {name: 'アンジャナフ亜種', nickname: '雷顎竜', weak1: '氷', weak2: '水',  breakPoint: 'なし' },
  {name: 'イヴェルカーナ', nickname: '冰龍', weak1: '火', weak2: '雷',  breakPoint: 'なし' },
  {name: 'イビルジョー', nickname: '恐暴竜', weak1: '龍', weak2: '雷',  breakPoint: 'なし' },
  {name: '怒り喰らうイビルジョー', nickname: '恐暴竜', weak1: '龍', weak2: 'なし',  breakPoint: 'なし', secondname: true },
  {name: 'イャンガルルガ', nickname: '黒狼鳥', weak1: '水', weak2: 'なし',  breakPoint: 'なし' },
  {name: '傷ついたイャンガルルガ', nickname: '傷痕', weak1: '水', weak2: 'なし',  breakPoint: 'なし', secondname: true },
  {name: 'ヴァルハザク', nickname: '屍套龍', weak1: '火', weak2: '龍',  breakPoint: 'なし' },
  {name: '死を纏うヴァルハザク', nickname: '死屍', weak1: '火', weak2: '龍',  breakPoint: 'なし', secondname: true },
  {name: 'ヴォルガノス', nickname: '溶岩竜', weak1: '水', weak2: '火',  breakPoint: 'なし' },
  {name: 'ウラガンキン', nickname: '爆鎚竜', weak1: '水', weak2: '龍',  breakPoint: '頭・腹部' },
  {name: 'オドガロン', nickname: '惨爪竜', weak1: '氷', weak2: '雷',  breakPoint: 'なし' },
  {name: 'オドガロン亜種', nickname: '兇爪竜', weak1: '氷', weak2: '雷',  breakPoint: 'なし' },
  {name: 'キリン', nickname: '幻獣', weak1: '火', weak2: '水氷',  breakPoint: '頭' },
  {name: 'クシャルダオラ', nickname: '鋼龍', weak1: '雷', weak2: '水竜',  breakPoint: 'なし' },
  {name: 'クルルヤック', nickname: '掻鳥', weak1: '水', weak2: 'なし',  breakPoint: 'なし' },
  {name: 'ジュラトドス', nickname: '泥魚竜', weak1: '雷', weak2: 'なし',  breakPoint: 'なし' },
  {name: 'ジンオウガ', nickname: '雷狼竜', weak1: '氷', weak2: 'なし',  breakPoint: 'なし' },
  {name: 'ジンオウガ亜種', nickname: '獄狼竜', weak1: '雷', weak2: 'なし',  breakPoint: 'なし' },
  {name: 'ゼノジーヴァ', nickname: '冥灯龍', weak1: 'すべて', weak2: 'なし',  breakPoint: 'なし' },
  {name: 'ムフェトジーヴァ', nickname: 'なし', weak1: 'すべて', weak2: 'なし',  breakPoint: 'なし' },
  {name: 'ゾラマグダラオス', nickname: '熔山龍', weak1: '水', weak2: '龍',  breakPoint: 'なし' },
  {name: 'ツィツィヤック', nickname: '眩鳥', weak1: '雷', weak2: '氷',  breakPoint: 'なし' },
  {name: 'ディアブロス', nickname: '角竜', weak1: '氷', weak2: '水',  breakPoint: 'なし' },
  {name: 'ディアブロス亜種',  nickname: '黒角竜', weak1: '氷', weak2: '水',  breakPoint: 'なし' },
  {name: 'ティガレックス',  nickname: '轟竜', weak1: '雷', weak2: '龍',  breakPoint: 'なし' },
  {name: 'ティガレックス亜種',  nickname: '黒轟竜', weak1: '水', weak2: '雷',  breakPoint: 'なし' },
  {name: 'ディノバルド',  nickname: '斬竜', weak1: '水', weak2: '氷',  breakPoint: 'なし' },
  {name: 'ディノバルド亜種',  nickname: '硫斬竜', weak1: '火', weak2: '雷',  breakPoint: 'なし' },
  {name: 'テオテスカトル',  nickname: '炎王龍', weak1: '水', weak2: '氷',  breakPoint: 'なし' },
  {name: 'ドスギルオス',  nickname: '痺賊竜', weak1: '水', weak2: 'なし',  breakPoint: 'なし' },
  {name: 'ドスジャグラス',  nickname: '賊竜', weak1: '火', weak2: 'なし',  breakPoint: 'なし' },
  {name: 'ドドガマル',  nickname: '岩賊竜', weak1: '雷', weak2: 'なし',  breakPoint: 'なし' },
  {name: 'トビカガチ',  nickname: '飛雷竜', weak1: '水', weak2: 'なし',  breakPoint: '頭・尻尾' },
  {name: 'トビカガチ亜種',  nickname: '飛毒竜', weak1: '雷', weak2: 'なし',  breakPoint: 'なし' },
  {name: 'ナナテスカリオ',  nickname: '炎妃龍', weak1: '氷', weak2: '龍',  breakPoint: 'なし' },
  {name: 'ナルガクルガ',  nickname: '迅竜', weak1: '雷', weak2: 'なし',  breakPoint: 'なし' },
  {name: 'ネルギガンテ',  nickname: '滅尽龍', weak1: '雷', weak2: 'なし',  breakPoint: 'なし' },
  {name: '悉くを滅ぼすネルギガンテ',  nickname: '滅尽龍', weak1: '龍', weak2: 'なし',  breakPoint: 'なし', secondname: true },
  {name: 'ネロミュール',  nickname: '溟龍', weak1: '火', weak2: '龍・氷',  breakPoint: '頭・前脚' },
  {name: 'パオウルムー',  nickname: '浮空竜', weak1: '火', weak2: '雷',  breakPoint: '頸袋・頭' },
  {name: 'パオウルムー亜種',  nickname: '浮眠竜', weak1: '水', weak2: '雷',  breakPoint: 'なし' },
  {name: 'バゼルギウス',  nickname: '爆鱗竜', weak1: '雷', weak2: 'なし',  breakPoint: 'なし' },
  {name: '紅蓮滾るバゼルギウス',  nickname: '紅蓮', weak1: '氷', weak2: '雷',  breakPoint: 'なし', secondname: true },
  {name: 'バフバロ',  nickname: '猛牛', weak1: '龍', weak2: 'なし',  breakPoint: '頭' },
  {name: 'プケプケ',  nickname: '毒妖鳥', weak1: '雷', weak2: 'なし',  breakPoint: '頭・尻尾' },
  {name: 'プケプケ亜種',  nickname: '水妖鳥', weak1: '氷', weak2: '雷',  breakPoint: '頭' },
  {name: 'プラキディオス',  nickname: '砕竜', weak1: '氷', weak2: '水',  breakPoint: 'なし' },
  {name: 'ブラントドス',  nickname: '凍魚竜', weak1: '火', weak2: 'なし',  breakPoint: 'なし' },
  {name: 'ベヒーモス',  nickname: '魔獣', weak1: 'なし', weak2: 'なし',  breakPoint: 'なし' },
  {name: 'ベリオロス',  nickname: '氷牙竜', weak1: '雷', weak2: '火',  breakPoint: '頭・尻尾' },
  {name: 'ボルボロス',  nickname: '土砂竜', weak1: '火', weak2: 'なし',  breakPoint: '前足・尻尾' },
  {name: 'マムタロト',  nickname: '爛輝龍', weak1: '雷', weak2: '水',  breakPoint: 'なし' },
  {name: 'ラージャン',  nickname: '金獅子', weak1: '氷', weak2: 'なし',  breakPoint: '頭・尻尾' },
  {name: 'ラドバルキン',  nickname: '骨鎚竜', weak1: '龍', weak2: 'なし',  breakPoint: '頭・脚' },
  {name: 'リオレイア',  nickname: '雌火竜', weak1: '龍', weak2: '雷',  breakPoint: 'なし' },
  {name: 'リオレイア亜種',  nickname: '桜火竜', weak1: '龍', weak2: '雷',  breakPoint: 'なし' },
  {name: 'リオレイア希少種',  nickname: '金火竜', weak1: '雷', weak2: 'なし',  breakPoint: '頭' },
  {name: 'リオレウス',  nickname: '火竜', weak1: '龍', weak2: '雷',  breakPoint: 'なし' },
  {name: 'リオレウス亜種',  nickname: '蒼火竜', weak1: '龍', weak2: '氷',  breakPoint: 'なし' },
  {name: 'リオレウス希少種',  nickname: '銀火竜', weak1: '水', weak2: 'なし',  breakPoint: '頭' },
  {name: 'レイギエナ',  nickname: '風漂竜', weak1: '雷', weak2: '火',  breakPoint: '頭・翼' },
  {name: '凍て刺すレイギエナ',  nickname: '氷霜をまとう', weak1: '火', weak2: '雷',  breakPoint: 'なし', secondname: true}
]


module.exports = datas
