'use strict'

const datas = [
    {
      name: 'アルバトリオン',
      nickname: '煌黒龍',
      weak1: 'なし',
      weak2: 'なし',
      咆哮: '大',
      風圧: 'なし',
      振動: 'なし',
      info: '炎活性中の弱点は【氷】\n氷活性中の弱点は【火】\n龍活性中の弱点は【龍】',
      url: ''
    },
    {
      name: 'アンイシュワルダ',
      nickname: '地啼龍',
      weak1: '氷',
      weak2: '水',
      咆哮: '大',
      風圧: '大',
      振動: '大',
      info: '',
      url: 'ラスボス...ニャ！'
    },
    {
      name: 'アンジャナフ',
      nickname: '蛮顎竜',
      weak1: '氷',
      weak2: '水',
      咆哮: '小',
      風圧: '小',
      振動: '小',
      info: '',
      url: ''
    },
    {
      name: 'アンジャナフ亜種',
      nickname: '雷顎竜',
      weak1: '氷',
      weak2: '水',
      咆哮: '小',
      風圧: 'なし',
      振動: '小',
      info: '帯電状態時は【水】に一番弱くなる',
      url: ''
    },
    {
      name: 'イヴェルカーナ',
      nickname: '冰龍',
      weak1: '火',
      weak2: '雷・龍',
      咆哮: '大',
      風圧: '大',
      振動: 'なし',
      info: '',
      url: ''
    },
    {
      name: 'イビルジョー',
      nickname: '恐暴竜',
      weak1: '雷・龍',
      weak2: '火・水',
      咆哮: '大',
      風圧: 'なし',
      振動: '大',
      info: '',
      url: ''
    },
    {
      name: '怒り喰らうイビルジョー',
      nickname: '恐暴竜',
      weak1: '雷・龍',
      weak2: '火・水',
      咆哮: '大',
      風圧: 'なし',
      振動: '大',
      secondname: true,
      info: '',
      url: ''
    },
    {
      name: 'イャンガルルガ',
      nickname: '黒狼鳥',
      weak1: '水',
      weak2: '龍',
      咆哮: '大',
      風圧: '小',
      振動: '大',
      info: '',
      url: ''
    },
    {
      name: '傷ついたイャンガルルガ',
      nickname: '傷痕',
      weak1: '水',
      weak2: '龍',
      咆哮: '大',
      風圧: '大',
      振動: '小',
      secondname: true,
      info: '',
      url: ''
    },
    {
      name: 'ヴァルハザク',
      nickname: '屍套龍',
      weak1: '火・龍',
      weak2: '氷',
      咆哮: '大',
      風圧: '大',
      振動: '小',
      info: '',
      url: ''
    },
    {
      name: '死を纏うヴァルハザク',
      nickname: '死屍龍',
      weak1: 'なし',
      weak2: '火・龍',
      咆哮: '大',
      風圧: '小',
      振動: 'なし',
      secondname: true,
      info: '',
      url: ''
    },
    {
      name: 'ヴォルガノス',
      nickname: '溶岩竜',
      weak1: '水',
      weak2: '雷・氷',
      咆哮: 'なし',
      風圧: 'なし',
      振動: 'なし',
      info: '硬化時も水が一番効く',
      url: ''
    },
    {
      name: 'ウラガンキン',
      nickname: '爆鎚竜',
      weak1: '水',
      weak2: '氷・龍',
      咆哮: '小',
      風圧: 'なし',
      振動: '大',
      info: '',
      url: ''
    },
    {
      name: 'オドガロン',
      nickname: '惨爪竜',
      weak1: '氷',
      weak2: '雷',
      咆哮: '小',
      風圧: 'なし',
      振動: 'なし',
      info: '',
      url: ''
    },
    {
      name: 'オドガロン亜種',
      nickname: '兇爪竜',
      weak1: '氷',
      weak2: '雷',
      咆哮: 'なし',
      風圧: 'なし',
      振動: 'なし',
      info: '',
      url: ''
    },
    {
      name: 'キリン',
      nickname: '幻獣',
      weak1: '火',
      weak2: '水・氷',
      咆哮: 'なし',
      風圧: 'なし',
      振動: 'なし',
      info: '',
      url: ''
    },
    {
      name: 'クシャルダオラ',
      nickname: '鋼龍',
      weak1: '雷',
      weak2: '龍',
      咆哮: '大',
      風圧: '龍風圧',
      振動: 'なし',
      info: '',
      url: ''
    },
    {
      name: 'クルルヤック',
      nickname: '掻鳥',
      weak1: '水',
      weak2: '火・雷・氷・龍',
      咆哮: 'なし',
      風圧: 'なし',
      振動: 'なし',
      info: '',
      url: ''
    },
    {
      name: 'ジュラトドス',
      nickname: '泥魚竜',
      weak1: '雷',
      weak2: 'なし',
      咆哮: 'なし',
      風圧: 'なし',
      振動: 'なし',
      info: '泥まとい時の弱点は【水】になる',
      url: ''
    },
    {
      name: 'ジンオウガ',
      nickname: '雷狼竜',
      weak1: '氷',
      weak2: '水',
      咆哮: '小',
      風圧: '小',
      振動: 'なし',
      info: '',
      url: ''
    },
    {
      name: 'ジンオウガ亜種',
      nickname: '獄狼竜',
      weak1: '雷',
      weak2: 'なし',
      咆哮: 'なし',
      風圧: 'なし',
      振動: 'なし',
      info: '',
      url: ''
    },
    {
      name: 'ゼノジーヴァ',
      nickname: '冥灯龍',
      weak1: 'なし',
      weak2: '火・龍',
      咆哮: '大',
      風圧: '龍風圧',
      振動: '大',
      info: '',
      url: ''
    },
    {
      name: 'ムフェトジーヴァ',
      nickname: '赤龍',
      weak1: '龍',
      weak2: 'すべて',
      咆哮: '大',
      風圧: '大',
      振動: '大',
      info: '傷をつけてから攻撃する',
      url: ''
    },
    {
      name: 'ゾラマグダラオス',
      nickname: '熔山龍',
      weak1: '水・龍',
      weak2: '氷',
      咆哮: '大',
      風圧: 'なし',
      振動: '大',
      info: '',
      url: ''
    },
    {
      name: 'ツィツィヤック',
      nickname: '眩鳥',
      weak1: '雷・氷',
      weak2: '火・水・龍',
      咆哮: 'なし',
      風圧: 'なし',
      振動: 'なし',
      info: '',
      url: ''
    },
    {
      name: 'ディアブロス',
      nickname: '角竜',
      weak1: '氷',
      weak2: '水・龍',
      咆哮: '大',
      風圧: '小',
      振動: '小',
      info: '',
      url: ''
    },
    {
      name: 'ディアブロス亜種',
      nickname: '黒角竜',
      weak1: '氷',
      weak2: '水',
      咆哮: '大',
      風圧: '小',
      振動: '小',
      info: '',
      url: ''
    },
    {
      name: 'ティガレックス',
      nickname: '轟竜',
      weak1: '雷',
      weak2: '龍',
      咆哮: 'なし',
      風圧: 'なし',
      振動: 'なし',
      info: '',
      url: ''
    },
    {
      name: 'ティガレックス亜種',
      nickname: '黒轟竜',
      weak1: '水',
      weak2: '雷',
      咆哮: 'なし',
      風圧: 'なし',
      振動: 'なし',
      info: '',
      url: ''
    },
    {
      name: 'ディノバルド',
      nickname: '斬竜',
      weak1: '水',
      weak2: '氷・龍',
      咆哮: '大',
      風圧: 'なし',
      振動: 'なし',
      info: '',
      url: ''
    },
    {
      name: 'ディノバルド亜種',
      nickname: '硫斬竜',
      weak1: '火',
      weak2: '雷・龍',
      咆哮: '大',
      風圧: 'なし',
      振動: 'なし',
      info: '結晶増加状態中は龍耐性が上がる',
      url: ''
    },
    {
      name: 'テオテスカトル',
      nickname: '炎王龍',
      weak1: '水・氷',
      weak2: 'なし',
      咆哮: '大',
      風圧: '大',
      振動: 'なし',
      info: '',
      url: ''
    },
    {
      name: 'ドスギルオス',
      nickname: '痺賊竜',
      weak1: '水',
      weak2: '氷',
      咆哮: 'なし',
      風圧: 'なし',
      振動: 'なし',
      info: '',
      url: ''
    },
    {
      name: 'ドスジャグラス',
      nickname: '賊竜',
      weak1: '火',
      weak2: '雷・氷',
      咆哮: '小',
      風圧: 'なし',
      振動: 'なし',
      info: '',
      url: ''
    },
    {
      name: 'ドドガマル',
      nickname: '岩賊竜',
      weak1: '雷',
      weak2: '水・氷',
      咆哮: '小',
      風圧: 'なし',
      振動: 'なし',
      info: '',
      url: ''
    },
    {
      name: 'トビカガチ',
      nickname: '飛雷竜',
      weak1: '水',
      weak2: '火・氷',
      咆哮: '小',
      風圧: 'なし',
      振動: 'なし',
      info: '',
      url: ''
    },
    {
      name: 'トビカガチ亜種',
      nickname: '飛毒竜',
      weak1: '雷',
      weak2: '火・氷',
      咆哮: '小',
      風圧: 'なし',
      振動: 'なし',
      info: '',
      url: ''
    },
    {
      name: 'ナナテスカトリ',
      nickname: '炎妃龍',
      weak1: '氷',
      weak2: '龍',
      咆哮: '大',
      風圧: '大',
      振動: 'なし',
      info: '',
      url: ''
    },
    {
      name: 'ナルガクルガ',
      nickname: '迅竜',
      weak1: '雷',
      weak2: '火',
      咆哮: '大',
      風圧: 'なし',
      振動: 'なし',
      info: '',
      url: ''
    },
    {
      name: 'ネルギガンテ',
      nickname: '滅尽龍',
      weak1: '雷',
      weak2: '龍',
      咆哮: '大',
      風圧: '大',
      振動: '小',
      info: '',
      url: ''
    },
    {
      name: '悉くを滅ぼすネルギガンテ',
      nickname: '滅尽龍',
      weak1: '龍',
      weak2: '雷',
      咆哮: '大',
      風圧: '大',
      振動: '小',
      secondname: true,
      info: '',
      url: ''
    },
    {
      name: 'ネロミェール',
      nickname: '溟龍',
      weak1: '火',
      weak2: '龍',
      咆哮: '大',
      風圧: 'なし',
      振動: 'なし',
      info: '',
      url: ''
    },
    {
      name: 'パオウルムー',
      nickname: '浮空竜',
      weak1: '火',
      weak2: '雷',
      咆哮: '小',
      風圧: '大',
      振動: 'なし',
      info: '',
      url: ''
    },
    {
      name: 'パオウルムー亜種',
      nickname: '浮眠竜',
      weak1: '水',
      weak2: '火',
      咆哮: '小',
      風圧: '大',
      振動: 'なし',
      info: '',
      url: ''
    },
    {
      name: 'バゼルギウス',
      nickname: '爆鱗竜',
      weak1: '雷',
      weak2: '氷・龍',
      咆哮: '大',
      風圧: '大',
      振動: '小',
      info: '',
      url: ''
    },
    {
      name: '紅蓮滾るバゼルギウス',
      nickname: '爆鱗竜',
      weak1: '氷',
      weak2: '雷',
      咆哮: '大',
      風圧: '大',
      振動: '小',
      secondname: true,
      info: '',
      url: ''
    },
    {
      name: 'バフバロ',
      nickname: '猛牛',
      weak1: '龍',
      weak2: '火',
      咆哮: '小',
      風圧: 'なし',
      振動: '小',
      info: '',
      url: ''
    },
    {
      name: 'プケプケ',
      nickname: '毒妖鳥',
      weak1: '雷',
      weak2: '火・氷',
      咆哮: '小',
      風圧: '小',
      振動: 'なし',
      info: '',
      url: ''
    },
    {
      name: 'プケプケ亜種',
      nickname: '水妖鳥',
      weak1: '氷',
      weak2: '雷',
      咆哮: '小',
      風圧: '小',
      振動: 'なし',
      info: '',
      url: ''
    },
    {
      name: 'プラキディオス',
      nickname: '砕竜',
      weak1: '氷',
      weak2: '水',
      咆哮: '大',
      風圧: 'なし',
      振動: '大',
      info: '',
      url: ''
    },
    {
      name: '猛り爆ぜるプラキディオス',
      nickname: '砕竜',
      weak1: '氷',
      weak2: '水',
      咆哮: '大',
      風圧: 'なし',
      振動: '大',
      info: '',
      url: ''
    },
    {
      name: 'ブラントドス',
      nickname: '凍魚竜',
      weak1: '火',
      weak2: '雷',
      咆哮: '小',
      風圧: '小',
      振動: 'なし',
      info: '',
      url: ''
    },
    {
      name: 'ベヒーモス',
      nickname: '魔獣',
      weak1: '龍',
      weak2: '水・氷',
      咆哮: '大',
      風圧: '小',
      振動: '大',
      info: '',
      url: ''
    },
    {
      name: 'ベリオロス',
      nickname: '氷牙竜',
      weak1: '火',
      weak2: '雷',
      咆哮: '大',
      風圧: '小',
      振動: '小',
      info: '',
      url: ''
    },
    {
      name: '氷刃佩くベリオロス',
      nickname: '風牙竜',
      weak1: '火',
      weak2: '雷・龍',
      咆哮: '大',
      風圧: 'なし',
      振動: 'なし',
      secondname: true,
      info: '',
      url: ''
    },
    {
      name: 'ボルボロス',
      nickname: '土砂竜',
      weak1: '火',
      weak2: '氷',
      咆哮: '小',
      風圧: 'なし',
      振動: 'なし',
      info: '泥まとい中は【水】が弱点になる',
      url: ''
    },
    {
      name: 'マムタロト',
      nickname: '爛輝龍',
      weak1: '氷',
      weak2: '水・龍',
      咆哮: 'なし',
      風圧: 'なし',
      振動: 'なし',
      info: '黄金付着中は【雷】が弱点になる',
      url: ''
    },
    {
      name: 'ミラボレアス',
      nickname: '黒龍',
      weak1: '龍',
      weak2: '火',
      咆哮: '大',
      風圧: '大',
      振動: 'なし',
      info: '',
      url: ''
    },
    {
      name: 'ラージャン',
      nickname: '金獅子',
      weak1: '氷',
      weak2: 'なし',
      咆哮: '大',
      風圧: 'なし',
      振動: '大',
      info: '闘気硬化移行時の咆哮は特大',
      url: ''
    },
    {
      name: '激昂したラージャン',
      nickname: '金獅子',
      weak1: '氷',
      weak2: 'なし',
      咆哮: '大',
      風圧: 'なし',
      振動: '小',
      secondname: true,
      info: '闘気硬化移行時の咆哮は特大',
      url: ''
    },
    {
      name: 'ラドバルキン',
      nickname: '骨鎚竜',
      weak1: '龍',
      weak2: '氷',
      咆哮: '小',
      風圧: 'なし',
      振動: '小',
      info: '',
      url: ''
    },
    {
      name: 'リオレイア',
      nickname: '雌火竜',
      weak1: '龍',
      weak2: '雷',
      咆哮: '小',
      風圧: '小',
      振動: 'なし',
      info: '',
      url: ''
    },
    {
      name: 'リオレイア亜種',
      nickname: '桜火竜',
      weak1: '龍',
      weak2: '雷',
      咆哮: '小',
      風圧: '小',
      振動: 'なし',
      info: '',
      url: ''
    },
    {
      name: 'リオレイア希少種',
      nickname: '金火竜',
      weak1: '雷',
      weak2: '水',
      咆哮: '大',
      風圧: '大',
      振動: 'なし',
      info: '',
      url: ''
    },
    {
      name: 'リオレウス',
      nickname: '火竜',
      weak1: '龍',
      weak2: '雷',
      咆哮: '大',
      風圧: '大',
      振動: 'なし',
      info: '',
      url: ''
    },
    {
      name: 'リオレウス亜種',
      nickname: '蒼火竜',
      weak1: '龍',
      weak2: '氷',
      咆哮: '大',
      風圧: '大',
      振動: 'なし',
      info: '',
      url: ''
    },
    {
      name: 'リオレウス希少種',
      nickname: '銀火竜',
      weak1: '水',
      weak2: '雷',
      咆哮: '大',
      風圧: '大',
      振動: 'なし',
      info: '',
      url: ''
    },
    {
      name: 'レイギエナ',
      nickname: '風漂竜',
      weak1: '雷',
      weak2: '火',
      咆哮: '大',
      風圧: '大',
      振動: 'なし',
      info: '',
      url: ''
    },
    {
      name: '凍て刺すレイギエナ',
      nickname: '氷霜をまとう',
      weak1: '火',
      weak2: '雷',
      咆哮: '大',
      風圧: '大',
      振動: 'なし',
      secondname: true,
      info: '',
      url: ''
    }
  ]

module.exports = datas
